.TH "C:/Users/Weppler/Documents/0_FACULTAD/5_QUINTO/PRIMER CUATRIMESTRE/PROGRAMABLE/MWeppler_1C_2026/firmware/projects/guia1_ej6/README.md" 3 "Guia 1 Ejercicio 6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Weppler/Documents/0_FACULTAD/5_QUINTO/PRIMER CUATRIMESTRE/PROGRAMABLE/MWeppler_1C_2026/firmware/projects/guia1_ej6/README.md
.SH SYNOPSIS
.br
.PP
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guia 1 Ejercicio 6 del código fuente\&.
